langage: ruby
rvm:
    - 2.4.2
cache: bundler
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - bundle exec rake db:migrate
    - npm install
script:
    - bundle exec rspec spec
